# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
target 'BuildingMaintenance' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ApiAI'
  pod 'IQKeyboardManagerSwift'
  pod 'JSQMessagesViewController'
  pod 'ARCL'
  pod 'CocoaLumberjack/Swift', :git => 'https://github.com/CocoaLumberjack/CocoaLumberjack', :branch => 'master'
  
end
